---
- name: nginx install and start
  hosts: all
  become: true
  tasks:
    - name: epel install
      yum:
        name: epel-release
        state: present
        
    - name: nginx install
      yum:
        name: nginx
        state: present
        
    - name: nginx start
      service:
        name: nginx
        state: started
