---
- name: deploy and restart
  hosts: Target
  become: true
  tasks:
    - name: copy file
      copy:
        src: /home/manage1/test.txt
        dest: /usr/share/nginx/html
      delegate_to: 192.168.56.11
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
